import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Card, Col, Row } from "react-bootstrap";
import styles from "../styles/Home.module.css";
import dataListProduk from "./../utils/list";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gramedium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Row>
          {dataListProduk.map((item, index) => {
            return (
              <Col key={index}>
                <Card
                  style={{
                    minWidth: "18rem",
                    maxWidth: "12rem",
                    margin: "8px",
                  }}
                  key={index}
                >
                  <Card.Body>
                    <Card.Img
                      variant="top"
                      src={item.image}
                      style={{
                        width: "100%",
                        height: "15vw",
                        objectFit: "contain",
                      }}
                    />
                    <Card.Title>
                      {item.name.length > 40
                        ? `${item.name.substring(0, 40)}...`
                        : item.name}
                    </Card.Title>
                    <Card.Text>Terjual : {item.terjual}</Card.Text>
                  </Card.Body>
                  <Card.Footer className="d-grid gap-2">
                    <Link
                      as={`/produk/${item.id}`}
                      href={`/produk?id=${item.id}`}
                      // target="_blank"
                    >
                      <a>Beli Sekarang</a>
                    </Link>
                  </Card.Footer>
                </Card>
              </Col>
            );
          })}
        </Row>
      </main>
    </div>
  );
};

export default Home;
