import Head from "next/head";
import Image from "next/image";
import { withRouter } from "next/router";
import { Button, Col, Container, Form, Row } from "react-bootstrap";
import styles from "/styles/Home.module.css";
import dataListProduk from "../utils/list";

const DetailProduk = withRouter((props) => {
  const data = dataListProduk.filter(
    (e) => e.id.toString() == props.router.query.id
  )[0];

  return (
    <div className={styles.container}>
      <Head>
        <title>Gramedium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        <Col xs={12} sm={12} md={6}>
          <Image
            src={data.image}
            alt={data.name}
            width="150px"
            height="150px"
            layout="responsive"
          ></Image>
        </Col>
        <Col xs={12} sm={12} md={6}>
          <div>{data.author}</div>
          <h1>{data.name}</h1>
          <h5>Deskripsi : </h5>
          <div>{data.desc}</div>
          <hr />
          <div>Jumlah terjual : {data.terjual}</div>
          <div>Stock tersedia : {data.stock}</div>
          <hr />
          <Form.Label htmlFor="inputPassword5">Qty</Form.Label>
          <Form.Control type="number" id="qty" defaultValue={1} />
          <br />
          <Row>
            <Col xs={12} sm={6} md={4} className="d-grid gap-2">
              <Button href={"#"} variant="outline-danger" size="sm">
                + KERANJANG
              </Button>
            </Col>
            <Col xs={12} sm={6} md={8} className="d-grid gap-2" size="sm">
              <Button href={"#"}>BELI SEKARANG</Button>
            </Col>
          </Row>
        </Col>
      </Row>
    </div>
  );
});

export default DetailProduk;
